version: "3"
services:
  postgres:
    image: postgres:10.0-alpine
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greenblog
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pg_data

volumes:
  psql_data:

## delete volume:  docker-compose down --volumes